In [1]:
import numpy as np
import pandas as pd

In [3]:
data_preprocessed = pd.read_csv('Absenteeism-preprocessed.csv')

In [5]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [4]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(), 1 , 0)

In [5]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['Excessive Absenteeism']=targets

In [7]:
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Age_1  Age_2  Age_3  Month_value  \
0           0         0         0         1      0      1      1            7   
1           0         0         0         0      0      0      1            7   
2           0         0         0         1      0      1      1            7   
3           1         0         0         0      0      1      1            7   
4           0         0         0         1      0      1      1            7   
..        ...       ...       ...       ...    ...    ...    ...          ...   
695         1         0         0         0      0      1      1            5   
696         1         0         0         0      1      0      1            5   
697         1         0         0         0      1      0      1            5   
698         0         0         0         1      0      1      1            5   
699         0         0         0         1      0      1      1            5   

     Day_of_the_Week  Transportation Expense  Distance to Work  \
0                  1                     289                36   
1                  1                     118                13   
2                  2                     179                51   
3                  3                     279                 5   
4                  3                     289                36   
..               ...                     ...               ...   
695                2                     179                22   
696                2                     225                26   
697                3                     330                16   
698                3                     235                16   
699                3                     291                31   

     Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                    239.554               30          0         2     1   
1                    239.554               31          0         1     0   
2                    239.554               31          0         0     0   
3                    239.554               24          0         2     0   
4                    239.554               30          0         2     1   
..                       ...              ...        ...       ...   ...   
695                  237.656               22          1         2     0   
696                  237.656               24          0         1     2   
697                  237.656               25          1         0     0   
698                  237.656               25          1         0     0   
699                  237.656               25          0         1     1   

     Absenteeism Time in Hours  Excessive Absenteeism  
0                            4                      1  
1                            0                      0  
2                            2                      0  
3                            4                      1  
4                            2                      0  
..                         ...                    ...  
695                          8                      1  
696                          3                      0  
697                          8                      1  
698                          2                      0  
699                          2                      0  

[700 rows x 18 columns]

### Creating Targets

In [8]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day_of_the_Week','Distance to Work', 'Daily Work Load Average'],axis=1)

In [9]:
data_with_targets is data_preprocessed #checking do thes variables refer to same/diff objects

False

In [10]:
data_with_targets.shape

(700, 14)

In [11]:
#data_with_targets.iloc[:,:16]
data_with_targets.iloc[:,:-1].head()

Reason_1  Reason_2  Reason_3  Reason_4  Age_1  Age_2  Age_3  Month_value  \
0         0         0         0         1      0      1      1            7   
1         0         0         0         0      0      0      1            7   
2         0         0         0         1      0      1      1            7   
3         1         0         0         0      0      1      1            7   
4         0         0         0         1      0      1      1            7   

   Transportation Expense  Body Mass Index  Education  Children  Pets  
0                     289               30          0         2     1  
1                     118               31          0         1     0  
2                     179               31          0         0     0  
3                     279               24          0         2     0  
4                     289               30          0         2     1

In [12]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

In [13]:
unscaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Age_1  Age_2  Age_3  Month_value  \
0           0         0         0         1      0      1      1            7   
1           0         0         0         0      0      0      1            7   
2           0         0         0         1      0      1      1            7   
3           1         0         0         0      0      1      1            7   
4           0         0         0         1      0      1      1            7   
..        ...       ...       ...       ...    ...    ...    ...          ...   
695         1         0         0         0      0      1      1            5   
696         1         0         0         0      1      0      1            5   
697         1         0         0         0      1      0      1            5   
698         0         0         0         1      0      1      1            5   
699         0         0         0         1      0      1      1            5   

     Transportation Expense  Body Mass Index  Education  Children  Pets  
0                       289               30          0         2     1  
1                       118               31          0         1     0  
2                       179               31          0         0     0  
3                       279               24          0         2     0  
4                       289               30          0         2     1  
..                      ...              ...        ...       ...   ...  
695                     179               22          1         2     0  
696                     225               24          0         1     2  
697                     330               25          1         0     0  
698                     235               25          1         0     0  
699                     291               25          0         1     1  

[700 rows x 13 columns]

### Standardizing of inputs

In [14]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

In [15]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy=True,with_mean=True,with_std=True)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

#### Alternate way to scale variables without including dummies

In [16]:
# dummies = unscaled_inputs[['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']]
# to_scale = unscaled_inputs[['Month Value',
#        'Day of the Week', 'Transportation Expense', 'Distance to Work',
#        'Age', 'Daily Work Load Average', 'Body Mass Index',
#        'Children', 'Pets']]
 
# scaler.fit(to_scale)
 
# scaled_inputs_no_dummies = scaler.transform(to_scale)
 
# dummies = dummies.to_numpy()
 
# scaled_inputs_alt = []
# for i in range(dummies.shape[0]):
#     scaled_inputs_alt.append(np.concatenate((scaled_inputs_no_dummies[i], dummies[i])))
    
# scaled_intputs_alt = np.array(scaled_outputs_alt)

In [17]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Age_1', 'Age_2',
       'Age_3', 'Month_value', 'Transportation Expense',
       'Body Mass Index', 'Education', 'Children', 'Pets'], dtype=object)

In [18]:
# columns_to_scale = ['Month_value', 'Day_of_the_Week',
#        'Transportation Expense', 'Distance to Work',
#        'Daily Work Load Average', 'Body Mass Index',
#        'Children', 'Pets']

columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Age_1', 'Age_2',
       'Age_3', 'Education']

In [19]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [20]:
absenteeism_scaler=CustomScaler(columns_to_scale)

In [21]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month_value', 'Transportation Expense',
                      'Body Mass Index', 'Children', 'Pets'])

In [22]:
scaled_input = absenteeism_scaler.transform(unscaled_inputs)

In [23]:
type(scaled_input)

pandas.core.frame.DataFrame

## Split into train & test and shuffle

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
x_train,x_test,y_train,y_test = train_test_split(scaled_input,targets, train_size=0.8 , random_state=20) #random state = some int as it will make shuffle sudo random 
# it wil shuffle the observation in same random way

In [26]:
# print(x_train , y_train)
# print(x_test , y_test)

In [27]:
print(x_train.shape , y_train.shape) # 80% data ==training
print(x_test.shape , y_test.shape) #20% data==test

(560, 13) (560,)
(140, 13) (140,)


# Logistic Regression Model

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [29]:
reg = LogisticRegression()

In [30]:
reg.fit(x_train , y_train)

LogisticRegression()

In [31]:
reg.score(x_train,y_train)

0.7625

#### Manually check accuracy

In [32]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,

In [33]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [34]:
model_outputs==y_train

array([ True,  True,  True, False,  True, False,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [35]:
np.sum(model_outputs==y_train)

427

In [36]:
accuracy = (np.sum(model_outputs==y_train))/model_outputs.shape[0]
accuracy

0.7625

#### Intercept and Coefficient

In [37]:
reg.intercept_

array([-1.30451393])

In [38]:
reg.coef_

array([[ 2.84871127,  0.8842582 ,  3.08979417,  0.89318617, -0.21345348,
         0.28021386, -0.51765475,  0.17121111,  0.64257437,  0.15769556,
        -0.15390119,  0.26143953, -0.1921654 ]])

In [39]:
features_name = unscaled_inputs.columns.values

In [40]:
summary_table = pd.DataFrame(columns=['Features_name'],data = features_name)
summary_table['Coefficient']=np.transpose(reg.coef_)
summary_table

Features_name  Coefficient
0                 Reason_1     2.848711
1                 Reason_2     0.884258
2                 Reason_3     3.089794
3                 Reason_4     0.893186
4                    Age_1    -0.213453
5                    Age_2     0.280214
6                    Age_3    -0.517655
7              Month_value     0.171211
8   Transportation Expense     0.642574
9          Body Mass Index     0.157696
10               Education    -0.153901
11                Children     0.261440
12                    Pets    -0.192165

In [41]:
summary_table.index=summary_table.index + 1
summary_table.loc[0]=['Intercept',reg.intercept_[0]]

In [42]:
summary_table['Odd_ratio']=np.exp(summary_table.Coefficient)
summary_table.sort_values(by = ['Odd_ratio'],ascending=False)

Features_name  Coefficient  Odd_ratio
3                 Reason_3     3.089794  21.972555
1                 Reason_1     2.848711  17.265517
4                 Reason_4     0.893186   2.442901
2                 Reason_2     0.884258   2.421188
9   Transportation Expense     0.642574   1.901369
6                    Age_2     0.280214   1.323413
12                Children     0.261440   1.298798
8              Month_value     0.171211   1.186741
10         Body Mass Index     0.157696   1.170810
11               Education    -0.153901   0.857357
13                    Pets    -0.192165   0.825170
5                    Age_1    -0.213453   0.807790
7                    Age_3    -0.517655   0.595916
0                Intercept    -1.304514   0.271304

## Testing Model

In [43]:
reg.score(x_test,y_test)

0.7214285714285714

In [45]:
predict_proba = reg.predict_proba(x_test)
predict_proba

array([[0.69235052, 0.30764948],
       [0.49376555, 0.50623445],
       [0.51336009, 0.48663991],
       [0.76891433, 0.23108567],
       [0.08482577, 0.91517423],
       [0.32009526, 0.67990474],
       [0.27609242, 0.72390758],
       [0.14494464, 0.85505536],
       [0.84576828, 0.15423172],
       [0.73236622, 0.26763378],
       [0.55243056, 0.44756944],
       [0.23644648, 0.76355352],
       [0.07777634, 0.92222366],
       [0.69358323, 0.30641677],
       [0.2211712 , 0.7788288 ],
       [0.63626251, 0.36373749],
       [0.61180562, 0.38819438],
       [0.60013459, 0.39986541],
       [0.2849566 , 0.7150434 ],
       [0.05899574, 0.94100426],
       [0.77082307, 0.22917693],
       [0.76891433, 0.23108567],
       [0.39135777, 0.60864223],
       [0.39135777, 0.60864223],
       [0.34491518, 0.65508482],
       [0.81113115, 0.18886885],
       [0.4566436 , 0.5433564 ],
       [0.8809596 , 0.1190404 ],
       [0.20013085, 0.79986915],
       [0.76891433, 0.23108567],
       [0.

In [46]:
predict_proba.shape

(140, 2)

In [47]:
predict_proba[:,1]

array([0.30764948, 0.50623445, 0.48663991, 0.23108567, 0.91517423,
       0.67990474, 0.72390758, 0.85505536, 0.15423172, 0.26763378,
       0.44756944, 0.76355352, 0.92222366, 0.30641677, 0.7788288 ,
       0.36373749, 0.38819438, 0.39986541, 0.7150434 , 0.94100426,
       0.22917693, 0.23108567, 0.60864223, 0.60864223, 0.65508482,
       0.18886885, 0.5433564 , 0.1190404 , 0.79986915, 0.23108567,
       0.45745543, 0.58698147, 0.70079763, 0.47184703, 0.23108567,
       0.52100007, 0.16071648, 0.7133772 , 0.39608761, 0.6041985 ,
       0.22251436, 0.39243612, 0.17434487, 0.38456981, 0.85038079,
       0.57239554, 0.6832018 , 0.30764948, 0.24426601, 0.21417243,
       0.52513471, 0.2478359 , 0.67990474, 0.30234905, 0.87873064,
       0.53063758, 0.84459428, 0.22515355, 0.2603011 , 0.26982281,
       0.73452147, 0.66917401, 0.29034584, 0.70803891, 0.22513137,
       0.28722576, 0.05764854, 0.16071648, 0.74405957, 0.3494642 ,
       0.16071648, 0.37500724, 0.87555068, 0.45577057, 0.59323

## Save Model

In [49]:
import pickle

In [51]:
with open('model','wb') as file:
    pickle.dump(reg,file)

In [52]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler,file)